### ISSUE TITLE
swagger-models missing primitive type

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-core#1560]
For a model whose schema is like such:

```yaml
ExampleEnum:
  type: string
  enum:
    - First
    - Second
```

We cannot describe this with `ModelImpl` as the enum property does not exist.

Either need to introduce a Primitive model or add the `enum` property to ModelImpl
