### ISSUE TITLE
Enums as first-class types?

### ISSUE THREAD

**Issue by delenius** [swagger-api/swagger-core#1658]
Currently, if I use an enum in Java, which then becomes one of the properties of one of the model classes, the enum gets treated as a set of allowed values for that particular property. For example, 

``` yaml
  Account:
    type: "object"
    properties:
      accountType:
        type: "string"
        enum:
        - "paid_account"
        - "free_account"
```

Why not treat enums as first-class types? Something like:

``` yaml
  Account:
    type: "object"
    properties:
      accountType:
        $ref: "#/definitions/AccountType"

...

  AccountType:
    type: "enum"
    enumMembers:
        - "paid_account"
        - "free_account"
```

This would have several benefits:
1. If the same enum is used in multiple places, we just get one definition instead of several.
2. More natural use of enums in generated client code.
