### ISSUE TITLE
Set defaultValue for Boolean

### ISSUE THREAD

**Issue by mayorbyrne** [swagger-api/swagger-core#181]
I'm not seeing a way to set a defaultValue of type boolean in the parameter declaration for an API.  Is this by nature, or am I missing something?

**Comment by childnode** [comment]
:information_source: 

```
 # ...
  properties:
    propname:
      type: boolean
      default: true

 # ...
```

will lead to `Boolean propname = null` in codegen 2.1.4
will lead to `Boolean propname = true` in codegen 2.2.1

so, fixed anywhere between and not (only) a ui bug ... or did I missed/misunderstood anything in this old issue?! anyway .. ;)
