### ISSUE TITLE
Request Object is immutable while passing parameters through Swagger UI

### ISSUE THREAD

**Issue by vaibhavshah846** [swagger-api/swagger-core#1850]
Hi,
I have written some django rest-framework APIs  and trying to document them using swagger.
My documentation for the POST method is as follows:
```
'''
            Create variations for any page using its campaign_id and page_id
            ---
            parameters:
                - name: name
                  description: Name of the Variation
                  required: true
                  type: string
                  
            type:
                message:
                    required: true
                    type: string
                variation:
                    required: true
                    type: object

            responseMessages:
                -   code: 201
                    message: Variation created successfully
                -   code: 400
                    message: Fail due to Bad request
                -   code: 404
                    message: Campaign or Page does not exist
                -   code: 500
                    message: Exception occured at server
                
            consumes:
                - application/json

            produces:
                - application/json
 '''
```

Inside my API,I am trying to add another field to the request object as follows:

`request.data['page'] = page.id`

The API works fine when I submit a request using the **Django REST Framework UI**.

But when I try to submit a request using Swaggers Try It feature for the API,I get this exception:
**QueryDict instance is immutable**

How to make the request object mutable when submitting request using Swagger UI?
