### ISSUE TITLE
How to add title field in model definitions

### ISSUE THREAD

**Issue by tdudzik** [swagger-api/swagger-core#2209]
Is it possible to add title field in the definition of a model? I would like to see something like this in generated swagger file:
```
definitions:
  FooResponse:
    type: "object"
    title: "Foo"
```
