### ISSUE TITLE
ModelConverter doesn't consider the private properties of the @Schema classes

### ISSUE THREAD

**Issue by ralphdoe** [swagger-api/swagger-core#2262]
When a property in a @Schema class is private the ModelConverter doesn't consider it in the Schema Object building.

@Schema Example class:
```java
static class SampleResponseSchema {
        @Schema(description = "the user id")
        private String id;
    }
```

Generated YAML:
```yaml 
content:
       application/json:
         schema:
           type: "object"
```

Expected YAML:
```yaml
content:
      application/json:
        schema:
          type: "object"
          properties:
            id:
              type: "string"
              description: "the user id"
```

@webron
