### ISSUE TITLE
IntegerSchema doesn't support Long values

### ISSUE THREAD

**Issue by frantuma** [swagger-api/swagger-core#2475]
Atm IntegerSchema only supports Integer, deserializing or assigning a Long value (e.g. defaultValue or enum) results in error or misbehaviour while casting to integer.

e.g.

```
        schema:
          type: integer
          format: int64
          enum:
          - 2147483647
          - 3147483647
          - 31474836475505055
```

when fixed, also related code in parser should be fixed/adapted, replacing code in :  https://github.com/swagger-api/swagger-parser/pull/536/files
