### ISSUE TITLE
swagger-core - ObjectProperty doesn't retain 'original' required properties

### ISSUE THREAD

**Issue by giuliopulina** [swagger-api/swagger-core#2479]
Hello,

I'm trying to implement some semantic validations rules for swagger, and I encountered a problem: ObjectProperty class doesn't retain the information about the properties that were defined as required.

Let's say we have a simple definition:

```
Client:
    type: object
    properties:
      address:
        type: object
        properties:
          addressLine:
            type: string
          town:
            type: string
        required:
          - unexisting
          - addressLine
      name:
        type: string
```

Currently, address.getRequiredProperties() won't contain 'unexisting', because required attribute are saved as boolean on the existing properties.

Would it be possible to retain the information in a separate field, like it's done in ModelImpl from swagger-models:

https://github.com/swagger-api/swagger-core/blob/5c91266e49572bbb71f6c15140738a898fee70b8/modules/swagger-models/src/main/java/io/swagger/models/ModelImpl.java#L231

 (even if ModelImpl doesn't have a getter for 'required'.. but at least I can use reflection there).

Thanks 
Giulio
