### ISSUE TITLE
Enums as query-params didn't show the options any more

### ISSUE THREAD

**Issue by JohneDoe** [swagger-api/swagger-core#2718]
| Q                                 | A
| --------------------------------- | -------
| Bug or feature request?           | Bug
| Which Swagger-Core version?       |2.0.0 (todays no snapshot via maven install)
| Which Java version?               | 8
| Which JAX-RS framework & version? | OSGi/CFX

Enums as Query params (TaskType) produced a ComboBox in SwaggerUi in earlier versions of the core.

This Combobox isnt shown any more because the values aren't in the yaml
 

Method

```

@GET
	@Path("/task")
	@Consumes(MediaType.APPLICATION_JSON)
	@Produces(MediaType.APPLICATION_JSON)
	@ApiResponse(responseCode = "200", content = {
			@Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(type = "array", implementation = TaskDTO.class))) })
	@ApiResponse(responseCode = "404", description = "User not found")
	@Operation(parameters = { @Parameter(in = ParameterIn.QUERY, name = "guid", required = true), })
	public Response getTasks(@QueryParam("tasktype") TaskType taskType, @Context SecurityContext securityContext) {
}
```

generated yaml
```

   operationId: getTasks
      parameters:
      - name: guid
        in: query
        required: true
        schema:
          type: string
      - name: tasktype
        in: query
 
```
