### ISSUE TITLE
Support to add properties in @Schema

### ISSUE THREAD

**Issue by MarvGilb** [swagger-api/swagger-core#2891]
For Maps it should be possible to set known properties to the generated documentation.

e.g.:
```
@Schema(description = "A map with known and custom properties.")
private Map<String, Object> map = new TreeMap<>();
```
returns an output like:
```
map:
  type: object
  additionalProperties:
    type: object
    description: A map with known and custom properties.
  description": A map with known and custom properties.
```

But required is an output with known properties like this:
```
map:
  type: object
  properties:
    knownValue1:
      type: string
    knownValue2:
      type: string
  additionalProperties:
    type: object
    description: A map with known and custom properties.
  description": A map with known and custom properties.
```
Therefore '@Schema' should get an additional variable that allows to override or add properties.
