### ISSUE TITLE
@XmlElement on an array-type attribute (@ArraySchema) should affect the attribute itself not its items

### ISSUE THREAD

**Issue by Treppenhouse** [swagger-api/swagger-core#2930]
| Q                                 | A
| --------------------------------- | -------
| Bug or feature request?           |  Bug
| Which Swagger-Core version?       |  2.0.3
| Which Java version?               | 1.8
| Which JAX-RS framework & version? | Jersey 2.27
 

I have a model property that looks like this (unrelated parts are left out):
```
@XmlElement(name = "myArrayField")
@ArraySchema(arraySchema=@Schema(description="my field description"), schema=@Schema(description="my item description"))
private Set<String> wrongNameField;
```

Its openAPI representation then looks like this:

```
myArrayField:
    description: "my field description"
    items:
        type: "string
        description: "my item description"
        xml:
            name: "myArrayField"
```

There are two things that bother me about this.
1. Why is the fact that I renamed the field from `wrongNameField` to `myArrayField` displayed here in form of a `xml:` property? Swagger correctly renamed the schema already (first line of this snippet). The fact that is comes from an XML Annotation is something I am not interested in and in fact something that I would like to hide from the consumers. Is there a way to suppress this? I only mean the ` xml:          name: "myArrayField"` part.
2. If not, then at least this `name` property should be on the level of the `myArrayField` itself and not on the level of its items. Compare that to the two properties of the `@ArraySchema` annotation: `schema` and `arraySchema`. The `@XmlElement(name= "myArrayField")` annotation should be "applied" to the `arraySchema` and NOT to the `schema`.
