### ISSUE TITLE
Default values in models are not set in downstream clients

### ISSUE THREAD

**Issue by spacether** [swagger-api/swagger-core#3065]
When one defines a swagger spec with a model per the below yaml
```
definitions:
  TypeHolder:
    type: object
    required:
      - string_item
      - number_item
      - integer_item
      - bool_item
      - array_item
      - object_item
    properties:
      string_item:
        type: string
        default: 'what'
        example: 'what'
      number_item:
        type: number
        default: 1.234
        example: 1.234
      integer_item:
        type: integer
        default: -2
        example: -2
      bool_item:
        type: boolean
        default: true
        example: true
```
Default values are returned by the OpenAPIParser for string and bool types only.
Default values are missing for array, integer, and number.

The definitions below seem to show that these defaults should be used in the models.

### swagger.io definition
https://swagger.io/specification/#schemaObject
default - The default value represents what would be assumed by the consumer of the input as the value of the schema if one is not provided. Unlike JSON Schema, the value MUST conform to the defined type for the Schema Object defined at the same level. For example, if type is string, then default can be "foo" but cannot be 1.

### The swagger 2.0 spec
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md and defines default as 
Schema Section:
default (Unlike JSON Schema, the value MUST conform to the defined type for the Schema Object)

### The openapi 3.02 spec
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md
Schema Section:
default - The default value represents what would be assumed by the consumer of the input as the value of the schema if one is not provided. Unlike JSON Schema, the value MUST conform to the defined type for the Schema Object defined at the same level. For example, if type is string, then default can be "foo" but cannot be 1.

Can the default key/values be added to model results of all swagger-parsing?
Can someone point me to where this parsing is done? I am having trouble finding the location in the code base. I am happy to submit a PR to fix this issue if someone can help me find the code doing it.
