### ISSUE TITLE
Cannot generate example for Query Parameter using @ExampleObject annotation

### ISSUE THREAD

**Issue by dublintech** [swagger-api/swagger-core#3270]
I need to generate something like this using swagger annotations

```
'/players':
    get:
      tags:
        - Player
      summary: ...
      parameters:
        ... 
        - name: sort
          in: query
          description: 'Comma separated list of sort parameters. Ascending by default, for descending preappend with <B>-</B>'
          schema:
            type: string
          examples:
            foo:
                summary: 'firstName, lastName' 
                description: 'sorts by firstName and then lastName'
            bar:
                summary: 'firstName, -lastName
                description: 'sorts by firstName and then lastName(descending)'
```

I try:

    @Operation(summary = "Get players"
    		, parameters = {
                    @Parameter(in = ParameterIn.QUERY, name = "sort"
                    	, description="Comma separated list of sort parameters. Ascending by default, for descending preappend with <B>-</B>"
                    	, examples = {
                    		@ExampleObject(name = "ex1" ,value = "firstName, lastName", summary = "sorts by name ascending"),
                    		@ExampleObject(name = "ex2", value = "firstName, -lastName", summary = "sorts by firstName and then lastName")
                    	})
            })
    @GET
    @Path("/players")
    

This generates the correct YAML but the examples and drop down don't appear in Swagger UI.
I am using Swagger UI version:

```
> JSON.stringify(versions)
"{"swaggerUi":{"version":"3.22.2","gitRevision":"g5628ff02","gitDirty":true,"buildTimestamp":"Wed, 22 May 2019 01:36:23 GMT","machine":"jenins-swagger-oss"}}"
```

when I try the same generated YAML in the online swagger editor, everything ok.  But doesn't work in this swagger UI for some reason.  Tried it on Chrome and IE.   Debugged the HTML and there's no reference to the dropdown. Also no JS errors.  So stuck.

Any ideas?
