### ISSUE TITLE
Doesn't infer subtypes when responding with/accepting a base class.

### ISSUE THREAD

**Issue by ethan92429** [swagger-api/swagger-core#3344]
When I have a class structure like:

```java
public class BaseClass{
    public String baseField;
}
```

```java
public class ChildAClass{
}
```

```java
public class ChildBClass{
}
```

I would expect anytime that the base class schema is referenced, a schema that looks like this is used:
```yaml
polymorphicBaseClass:
    oneOf:
        - $ref : '#/components/schemas/childAClass'
        - $ref : '#/components/schemas/childAClass'
        - $ref : '#/components/schemas/justBaseClass'
```
And the `justBaseClass` schema would look something like:
```yaml
justBaseClass:
    type:object
    properties:
        baseField:
            type: string
```

The current structure never infers these subclasses in the parent. Instead, currently the child always includes the parent in an allOf statement. Since that is the current behavior, we can't just _add_ the onsOf to point at the children or else we'll get into a circular reference that would be semantically wrong. I believe to get the right behavior, a concrete class needs to generate two different schemas - one polymorphic schema that points to all of the subclasses as well as just the raw base class, and just the raw base class. That would break the circular issue and remain rather clean, as one would still be able to refer to just the class itself without the subtypes. 

Is my assessment correct that this is currently not possible? @fehguy and @frantuma . And if it indeed isn't, I can work on implementing it - and is the implementation I'm suggesting the right way to approach this?

**Comment by ethan92429** [comment]
Thinking about this more, it may be that this behavior should be implied for when a discriminator and mapping field is present without any of the compositional keywords on the item. However - I don't see that documented anywhere. To be clear, I mean when an schema looks like: 
```yaml
    BaseClass:
      type: object
      properties:
        baseField:
          type: string
      discriminator:
        propertyName: discriminatorString
        mapping:
          ChildAClass: '#/components/schemas/ChildAClass'
          ChildBClass: '#/components/schemas/ChildBClass'
```
If that was the rule, to avoid meaningless circles, any tool consuming the schema would have to know that there are two different ways to view the schema - either as polymorphically, in which it resolves to either the base class alone OR the schemas pointed to in the mapping. The other way to view it would be JUST the base class, such as when it is referenced from the child itself.

Thoughts? I think that would be a change to the spec, but the earlier change I mentioned would work well with just swagger-core. I'd love to hear your thoughts!
