### ISSUE TITLE
String type example cutting the value when started with digit

### ISSUE THREAD

**Issue by chameleon82** [swagger-api/swagger-core#3365]
in my dto i have annotation
```
    @Schema(
      required = true,
      title = "Cron formatted invoice schedule",
      example = "0 0 5 * *"
    )
    invoiceDateCron: String,
```
but when swagger producing yaml is see
```
       invoiceDateCron:
          title: Cron formatted invoice schedule
          type: string
          example: "0"
```

This behaviour appearing only when i put leading digit with space after.
checked on swagger versions `2.0.8` and `2.1.0`
