### ISSUE TITLE
Property Level Required in OpenAPI 3

### ISSUE THREAD

**Issue by itmuckel** [swagger-api/swagger-core#3383]
I'm sorry if this came up before, but why has the property level required attribute been removed?

```yaml
    MyObject:
      type: object
      properties:
        ordinal:
          type: integer
        text:
          type: string
      required:
        - ordinal
        - text
```

In this case I have to remember to change the fields in the `required` section when I change the name of a field. This isn't dry and can easily be forgotten. Also I get no error when there are `required` fields that aren't even in the object. So my question is, what is the reasoning behind this? Is there an attempt to bring property level `required`s back?
