### ISSUE TITLE
NullPointerException caused by returning null in method from Parameter returning Boolean

### ISSUE THREAD

**Issue by cvgaviao** [swagger-api/swagger-core#3386]
Take a look in the parameter bellow:
```
    ParamQ_RetailUnitId:
      description: The id of one of the retail's units.
      in: query
      name: unit-id
      schema:
        format: int32
        type: integer
         
```
It doesn't declare a "required: false" and because of this missing, the property `required` of an object of class io.swagger.v3.oas.models.parameters.Parameter will have a null value as soon its parsed.

But the method below MUST not return null, it must return Boolean.FALSE !
```
    public Boolean getRequired() {
        return required;
    }

```
