### ISSUE TITLE
Using Swagger Annotations to generate XML namespace information

### ISSUE THREAD

**Issue by stevenwall** [swagger-api/swagger-core#3420]
My XML request looks like this:
```
    <ns1: MyRequest ns1="http://abc.com/api/2.0">:
        <reference>A request to my endpoint</reference>
   </ns1:MyRequest>
```

I believe it should be modeled in Swagger/OpenAPI 3 spec as follows:

```
    MyRequest:
      type: object
      properties:
        reference:
          type: string
          xml:
            name: reference
      xml:
        prefix: cs
        namespace: https://abc.com/api/2.0
```

Is it possible to annotate my MyRequest.java class appropriately using JAXB or Swagger annotations to get the prefix and namespace entries in the generated OpenAPI spec?
