### ISSUE TITLE
Enum names not overriden with @JsonProperty or @JsonValue

### ISSUE THREAD

**Issue by joschi** [swagger-api/swagger-core#3552]
We're using `io.swagger.core.v3:swagger-maven-plugin:2.1.2` (and Jackson 2.10.4) in our project to generate an OpenAPI v3 specification of our code.

As part of our models, we have some enum classes in which we override the serialized/deserialized enum values with `@JsonProperty` or `@JsonValue` but the generated OpenAPI specification is always referring to the enum names ([`Enum#name()`](https://docs.oracle.com/javase/8/docs/api/java/lang/Enum.html#name--)).

This looks like a regression from #2707 which was closed with (allegedly) solving the issue in Swagger 1.5.x.

## Example class with `@JsonProperty`

Java code:
```java
public enum SomeEnum {
  @JsonProperty("num-one")
  NUMONE,
	
  @JsonProperty("num-two")
  NUMTWO
}
```

Expected results in the OpenAPI specification:
```yaml
someEnum:
  type: string
  enum:
    - num-one
    - num-two
```

Actual results in the OpenAPI specification:
```yaml
someEnum:
  type: string
  enum:
    - NUMONE
    - NUMTWO
```

## Example class with `@JsonValue`

Java code:
```java
public enum SomeEnum {
  NUMONE("num-one"), NUMTWO("num-two");

  private final String value;

  public SomeEnum(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }
}
```

Expected results in the OpenAPI specification:
```yaml
someEnum:
  type: string
  enum:
    - num-one
    - num-two
```

Actual results in the OpenAPI specification:
```yaml
someEnum:
  type: string
  enum:
    - NUMONE
    - NUMTWO
```
