### ISSUE TITLE
Version 2.1.3 Changed YAML multi-line string format

### ISSUE THREAD

**Issue by RohanNagar** [swagger-api/swagger-core#3626]
Hi all,

I was trying to update swagger version from 2.1.2 to 2.1.3 and was trying to figure out why my build was failing (https://github.com/RohanNagar/thunder/pull/799). After some investigation I noticed that the way the YAML is generated is slightly different. See here for the diff (version 2.1.2 as the original and version 2.1.3 as the change): https://www.diffchecker.com/ebLOoDUV

Here's a snippet:

Version 2.1.2:

```yaml
parameters:
      - name: password
        in: header
        description: The password of the user, necessary if the headerPasswordCheck
          option is enabled.
        schema:
          type: string
```

Version 2.1.3:

```yaml
parameters:
      - name: password
        in: header
        description: "The password of the user, necessary if the headerPasswordCheck\
          \ option is enabled."
        schema:
          type: string
```

I'm wondering if this is expected and to make sure this is valid YAML, as the javascript YAML parser I use seems to have a problem with this new format. Thanks!
