### ISSUE TITLE
Missing "properties" attribute in @Schema annotation 

### ISSUE THREAD

**Issue by dmaio** [swagger-api/swagger-core#3633]
I'd like to define some properties as mentionned in https://swagger.io/docs/specification/data-models/data-types/#object

```
type: object
properties:
  myprop:
    type: string
```
The Schema class has the Map<String, Schema> properties attribute but the annotation doesn't support it.
