### ISSUE TITLE
JSR-303 validation support for Swagger 2.x

### ISSUE THREAD

**Issue by debargharoy** [swagger-api/swagger-core#3731]
I've the following piece of code
```java
@GET
@Path("/cart")
@Operation(summary = "Get cart items", description = "Paging follows RFC 5005.")
public List<Item> getCart(
            @QueryParam("pageSize") //
            @DefaultValue("50") //
            @Min(1) @Max(200)
            @Parameter(description = "Number of items per page. Range[1, 200]") //
            final int pageSize
) {
    ...
}
```
and the output is as below
![image](https://user-images.githubusercontent.com/30570555/98109383-79737d80-1ec3-11eb-8950-ce71215b70f9.png)

**Current behaviour**

And the query is executed successfully. 

**Expected behaviour**

Swagger should restrict the input in the given range

Generated spec file
```yaml
 /cart:
    get:
      summary: Get cart items
      description: Paging follows RFC 5005.
      parameters:
      - name: pageSize
        in: query
        description: Number of items per page. Range[1, 200]
        schema:
          type: integer
          format: int32
          default: 50
```
From the spec, it's clear that Swagger 2.x didn't consider the `@Min` and `@Max` from the code.

Did I do something wrong or it's not supported?
