### ISSUE TITLE
Enhancement: Allow to override required attribute when @NotNull is set

### ISSUE THREAD

**Issue by mathias-ewald** [swagger-api/swagger-core#3909]
When I annotate an entity property with @NotNull, I required this property to be set on the persistence layer. For most situations, it makes sense to assume it is required on the REST layer, too. In my scenario, I have such a property that is not required on the REST layer, is required in the persistence layer but will be filled in by application logic if not set.

Any entity with a @NotNull property will do to reproduce:

```
public class Pet {
	@NotNull
	private String name;
}
```
```
    Pet:
      required:
      - name
      type: object
      properties:
        name:
          type: string
```

I would expect an annotation like @Schema(required = false) on the name property to override the the @NotNull in the context of the api doc.
