### ISSUE TITLE
OpenAPI Java POJO Does Not Support Array Parameters

### ISSUE THREAD

**Issue by rickerju** [swagger-api/swagger-core#3950]
Currently the the schema.java class used by parameters in the OpenAPI java POJO does not contain a field for `items` when the parameter is of type "array"

There currently is no way to support this style of parameter with a POJO
```yaml
 parameters:
      - name: foo
        in: query
        schema:
          type: array
          items:
            type: string
```

This is causing major issues for us as we serve a swagger page from these POJOs.

Please add an optional `items` field to the Schema.java class that is used by the Parameter.java class
