### ISSUE TITLE
Incorrect path parameters when using JAXRS subresources

### ISSUE THREAD

**Issue by JanMalch** [swagger-api/swagger-core#3952]
When using JAXRS subresources with path parameters the listed parameters are incorrect.

```java
@Path("group")
@Tag(name = "Group")
public class GroupResource {
  @Inject private PersonResource personResource;
  @Path("{groupId}")
  public PersonResource get() { return this.personResource; }
}

@Path("")
@Tag(name = "Person")
public class PersonResource {
  @GET
  @Path("persons")
  public Response findPersons(@PathParam("groupId") String groupId) { return Response.ok().build(); }
}
```

The resulting YAML will have the correct paths but the parameters are wrong.

```yaml
paths:
  # correct path but incorrect parameters
  persons:
    get:
      parameters:
      - in: path
        name: groupId
        required: true
  # this one is correct
  group/{groupId}/persons:
    get:
      parameters:
      - in: path
        name: groupId
        required: true
```

Is there any way around it?

Using version `2.1.9` of `swagger-core`,  `swagger-jaxrs2` and `swagger-maven-plugin`.
