### ISSUE TITLE
Find the $ref to a propertie inside a schema

### ISSUE THREAD

**Issue by ThiagoFrazao** [swagger-api/swagger-core#3971]
Hello,
i have two schemas where in one of them i have the property _importantProperty_ and in the other i have a $ref to said property.
Something like this:
SchemaA
```
SchemaA:
      type: object
      properties:
        importantProperty:
          type: string
          maxLength: 3
          pattern: '\d{3}|^NA$'
          description: ''
          example: '001'
```
SchemaB
```
SchemaB:
type: object
properties:
     importantProperty:
          $ref: '#/components/schemas/SchemaA/properties/importantProperty'
```
but once the document is parsed i can't find the schema for _importantProperty_ in the Map<String, Schema>.

My current code is:

```
private Schema getSchemaFromRefName(String schemaRef) {
    String schemaName = (String) RefUtils.extractSimpleName(schemaRef).getKey();
    return oas.getComponents().getSchemas().get(schemaName);
}
```
Where _schemaRef_ is #/components/schemas/SchemaA/properties/importantProperty. 
The method returns _NULL_ and I don't have control over the OAS to simply move the schema to _components/schemas_.

There is a way to find those $ref?
