### ISSUE TITLE
Invalid schema for nested BeanParam (query) parameters

### ISSUE THREAD

**Issue by DanPetras** [swagger-api/swagger-core#3973]
Hi, there seems to be issue with processing nested @javax.ws.rs.BeanParam objects / parameters.

I'm using io.swagger.core.v3.swagger-gradle-plugin version 2.1.9
Jersey version 2.27
Jackson version 2.9.9

gradle **resolve** task generates:

```
/api/nested:
  get:
    requestBody:
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/NestedParams'
```
with 
```
components:
  schemas:
    NestedParams:
      type: object
```
instead of
```
/api/normal:
  get:
    parameters:
      in: query
      name: page
      schema:
        type: integer
        format: int32
        default: -1
      in: query
      name: size
      schema:
        type: integer
        format: int32
      ...
```

You can see whole output as [yaml](https://github.com/DanPetras/NestedBeanParams/blob/master/openapi.yaml) or [json](https://github.com/DanPetras/NestedBeanParams/blob/master/openapi.json).

I created example project at [DanPetras/NestedBeanParams](https://github.com/DanPetras/NestedBeanParams).

I also tried older versions of swagger-gradle-plugin but with no success.
Is this a bug or am I doing something wrong here?

The "old swagger" (io.swagger:swagger-jersey2-jaxrs:1.6.2) is working as expected.
