### ISSUE TITLE
JBoss EAP 7.2.9: Swagger v2.1.10 leads to IOExceptions "To many open files"

### ISSUE THREAD

**Issue by AndreasIgelCC** [swagger-api/swagger-core#4001]
Hi together,

swagger is a great tool and I do not want to miss it in my projects any more. Unfortunately we got problems with the new versions of Swagger (starting from 2.1.2). It seems like the generation of openapi.json leads to a massive number of new opened files, which are not closed afterwards. 

Environement:
* JBoss EAP 7.2.9
* openjdk version "1.8.0_131"
* Resteasy 3.15.1
* Spring 5.3.8

Configuration via ApplicationConfig:
```java
import javax.ws.rs.core.Application;

public class ApplicationConfig extends Application {
  public ApplicationConfig() {
    SpringApplicationContext.autowire(this);
  }

  @Override
  public Set<Class<?>> getClasses() {
    Set<Class<?>> resources = new java.util.HashSet<>();
    //other stuff
    resources.add(io.swagger.v3.jaxrs2.SwaggerSerializers.class);
    resources.add(io.swagger.v3.jaxrs2.integration.resources.AcceptHeaderOpenApiResource.class);
    resources.add(io.swagger.v3.jaxrs2.integration.resources.OpenApiResource.class);
    return resources;
  }

  //other stuff
}
```

OpenApi-Configuration in openapi-configuration.yaml:
```yaml
## YAML Template.
---
resourcePackages:
- de.example.project.spezific.exampleservice
- de.example.project.plattform.webservices
prettyPrint: true
cacheTTL: 0
openAPI:
  info:
    version: ${project.version}
    title: Test Service
    description: 'Webservice zum Ansprechen der Test-Schnittstelle.'
    contact:
      email: andreas@example.xml
  components:
    securitySchemes:
      BasicAuth:
        type: http
        scheme: basic
  security:
  - BasicAuth: []
  servers:
  - url: /example-service/
```
We defined both resourcePackages because we share some service-endpoints via multiple modules for plattform topics.

Way of testing the topic:
1. Watching open files: watch "lsof | grep java | wc -l"
2. Opening http://server/example-service/openapi.json

Result (with versions from 2.1.2 beginning):
- number of open files is around 5.000-8.000 higher then before (not reduced any more)
- each further Call on http://server/example-service/openapi.json increases the Number of open files

We tracked the problem down to the the update of swagger from 2.1.1 to 2.1.2. Maybe it is a crossside problem from classpath library update or from changes in initializer?

Thank you!

Best Regards,
Andreas
