### ISSUE TITLE
Appending index

### ISSUE THREAD

**Issue by Comjens** [swagger-api/swagger-core#4040]
Hi, 

I'm having a problem when i am generating a yaml file using io.swagger.v3 and swagger-maven-plugin.

I have two different classes that have some of the same method names and unfortunately one gets appended _1 on the operation id. 
i.e. .yaml:
```YML
 /cats/report/{id}:
    get:
      tags:
      - cats
      summary: Get report (NOT IMPLEMENTED)
      operationId: getReportById
```
```YML
  /dogs/report/{id}:
    get:
      tags:
      - Dogs
      summary: Get report
      operationId: getReportById_1
      parameters:
```
Here is my config:

```
<plugin>
  <groupId>io.swagger.core.v3</groupId>
  <artifactId>swagger-maven-plugin</artifactId>
  <version>2.1.11</version>
  <configuration>
      <outputFileName>openapi</outputFileName>
      <outputPath>${project.build.directory}/${project.build.finalName}/apidoc</outputPath>
      <outputFormat>JSONANDYAML</outputFormat>
      <resourcePackages>
          <package>dk.oes.refusion.rest</package>
      </resourcePackages>
      <prettyPrint>TRUE</prettyPrint>
  </configuration>
  <executions>
      <execution>
          <phase>compile</phase>
          <goals>
              <goal>resolve</goal>
          </goals>
      </execution>
  </executions>
</plugin>
 ```
