### ISSUE TITLE
When a field has @field:Schema annotation, it is not listed as required

### ISSUE THREAD

**Issue by ruiminamywang** [swagger-api/swagger-core#4089]
With micronaut 2.5.13, micronaut-openapi 2.6.2, language: Kotlin
```
@Introspected
data class SomeRequest(
    @field:Schema(description = "description ...")
    @field:NotBlank
    val name: String,
    @field:Schema(description = "description ...")
    val description: String? // Optional

```
The code above generates openAPI specs like
```
    SomeRequest:
      required:
      - name
      type: object
      properties:
        name:
          minLength: 1
          type: string
          description: description ...
        description:
          type: string
          description: description ...
          nullable: true
```

However, after upgrading to micronaut 3.1.4, and micronaut-openapi 3.2.0, `name` become optional after auto-generating the openAPI specs:
```
    SomeRequest:
      type: object
      properties:
        name:
          minLength: 1
          type: string
          description: description ...
        description:
          type: string
          description: description ...
          nullable: true
```

These lines are removed
```
      required:
      - name
```

Is this expected behavior?
