### ISSUE TITLE
@SecurityScheme requires #type when #ref is used

### ISSUE THREAD

**Issue by dansiviter** [swagger-api/swagger-core#4100]
It's not possible to define a reference with `@SecurityScheme` without also defining a type.

```java
@SecurityScheme(ref = "another.yaml#/components/securitySchemes/blagh")  // <-- Compilation error
```
More strange is that `#name` can be `null` even though it's required at all times so it can be referred to by `@SecurityRequirement`. Therefore, this would render as:

```yaml
components:
  securitySchemes:
    ?????:  # <-- indeterminable value
      $ref: 'another.yaml#/components/securitySchemes/blagh'
```

It is possible to use a ` SecuritySchemaType#DEFAULT` value, but it's not clear if this is the correct usage:

```java
@SecurityScheme(type = SecuritySchemaType.DEFAULT, ref = "another.yaml#/components/securitySchemes/blagh") 
```
Which would give:
```yaml
components:
  securitySchemes:
    ?????:  # <-- still indeterminable value
      type: ""
      $ref: 'another.yaml#/components/securitySchemes/blagh'
```

It appears [OAI/OpenAPI-Specifications#2064](/OAI/OpenAPI-Specification/issues/2064) shows how this should appear.

Therefore, I believe `#name` should have no default and be mandatory, and `#type` should default to `SecuritySchemaType#DEFAULT`.
