### ISSUE TITLE
anyOf default types (String, Number, Boolean) 

### ISSUE THREAD

**Issue by Santobert** [swagger-api/swagger-core#4290]
## Situation

I have a complex object with an attribute of type Object. Allowed values are string, number or boolean. I would like to achieve something like the following:

```yaml
    Point:
      type: object
      properties:
        value:
          type: object
          description: "A string, a number or a boolean"
          anyOf:
          - type: string
          - type: number
          - type: boolean
```

Therefore, I've chosen the following annotations:

```java
public class Point {

	@Schema(description = "A string, a number or a boolean", anyOf = { String.class, Number.class, Boolean.class })
	private Object value;
}
```

Actual Output

```yaml
    Point:
      type: object
      properties:
        value:
          type: object
          description: "A string, a number or a boolean"
          anyOf:
          - type: object
          - type: object
          - type: object
```

## Environment

- Java 17
- Jersey 3.0.8
- Swagger Version 2.2.4
- `-jakarta` packages
