### ISSUE TITLE
Swagger duplicates operation in spec

### ISSUE THREAD

**Issue by alizaga** [swagger-api/swagger-core#4380]
Q | A
-- | --
Bug or feature request? | Bug
Which Swagger-Core version? | 2.2.8
Which Java version? | 1.8.0_362
Which JAX-RS framework & version? | jax-rs 2.1.1 & jersey 2.39

We have an interface defined in this way:
```java
public interface OperationSpec {

  @Operation(
      operationId = "spec.random")
  @GET
  @Path("/operation")
  @Produces(ApiMediaType.JSON)
  Response getOperation();
}
```
  
And an implementation of `OperationSpec`:
```java
@Path("/operations")
public class Operation implements OperationSpec {
  @Override
  @JsonView(Views.API.V1.class)
  public Response getOperation() {
      ...
  }
}
```

For no reason, swagger is generating a spec file with two duplicate operations:
```yml
'/operations/operation':
    get:
      operationId: spec.random
...

'/operation':
    get:
      operationId: spec.random_1
```

Is there any reason for this?
