### ISSUE TITLE
Scala public fields not shown in schema 

### ISSUE THREAD

**Issue by nickkhine** [swagger-api/swagger-core#4496]
Hi, I am wondering how we can show public fields from scala classes in the ModelConverters generated schema. 

For example, if I have the class:

```
class NickTest {
  val myVal : String = "myVal"

  def getFieldthatWillGenerate: String = ""
}

```
and I try to generate a schema from it 
```

    public void generateSourceTableSchema() {
        final ModelConverters converters = new ModelConverters();
        final Map<String, Schema> schema = converters.getInstance().readAll(NickTest.class);
        System.out.println(Yaml.pretty(schema));
    }
   
```
I get the output of: 

```
NickTest:
  type: object
  properties:
    fieldthatWillGenerate:
      type: string

```

but would expect "myVal" to be listed in the generated schema
