### ISSUE TITLE
How do we define authorization in spec?

### ISSUE THREAD

**Issue by SpecialYang** [swagger-api/swagger-core#4716]
According to the official documentation, the current Swagger API standards only support authentication, not authorization. 

For example, with [API-Key authentication](https://swagger.io/docs/specification/authentication/api-keys/), we can define authentication policy with API-Key at the API or Operation level, but we cannot specify which API-Key can access a particular operation. How should we use API-Key for authorization?
```
openapi: 3.0.0
...
# 1) Define the key name and location
components:
  securitySchemes:
    ApiKeyAuth:        # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: X-API-KEY  # name of the header, query parameter or cookie
# 2) Apply the API key globally to all operations
security:
  - ApiKeyAuth: [] 
```

Can we allow specific api-keys which can access one api? From a security perspective, perhaps we can reference a secret or a configuration center in the spec for whitelisted API-Key discovery?

**Comment by ewaostrowska** [comment]
Hi @SpecialYang, 
OpenAPI specs describe **authentication**, but not **authorization**. This is by design and there are no plans at the moment to change this
- The spec is typically public (or shared broadly with consumers)
- Embedding actual secrets or key lists in it would be a security anti-pattern

What you can do instead is to point where the authorization rules live. The **x- extension** mechanism exists exactly for this. Add an extension to the security scheme that references your secrets manager etc.. Tools, gateways, and middleware can then read that pointer and enforce the actual rules:
```
  components:                                                                                                                                                                                                                                                                                                           
    securitySchemes:                                                                                                                                                                                                                                                                                                      
      ApiKeyAuth:                                                                                                                                                                                                                                                                                                       
        type: apiKey
        in: header                                                                                                                                                                                                                                                                                                        
        name: X-API-KEY
        x-authorization-config:                                                                                                                                                                                                                                                                                           
          config-ref: vault://secrets/api-keys-whitelist                                                                                                                                                                                                                                                                
          discovery-url: https://config.internal/api-key-policies  
```                                                                                                                                                                                                                                                       
Hope this answer is helpful for you :)
