### ISSUE TITLE
@Schema oneOf config is ignored when generate the api-docs

### ISSUE THREAD

**Issue by abccbaandy** [swagger-api/swagger-core#4732]
````java
    @Schema(oneOf = {Child1.class, Child2.class})
    private Parent obj;
````

The result is something like this
````json
                    "MyPojo": {
                        "oneOf": [
                            {
                                "$ref": "#/components/schemas/Child1"
                            },
                            {
                                "$ref": "#/components/schemas/Child2"
                            },
                            {
                                "$ref": "#/components/schemas/Child3"
                            }
                        ]
                    },
````

Seems the result does not come from my config.

Also I think oneOf should take string(`$ref`) instead class?

**Comment by ponelat** [comment]
@abccbaandy could you clarify what your expectations are? And provide a complete example.

**Comment by albanf** [comment]
Here is another example where the Java type of the field is used in addition to the `oneOf`/`anyOf` attribute:
```
public class MyParameter {

    @Schema(description = "",
            anyOf = {Integer64.class, StringDateTime.class},
            nullable = true)
    Instant date;

    @Schema(type = "integer", format = "int64", description = "Unix timestamp")
    private static class Integer64 {}

    @Schema(type = "string", format = "date-time", description = "ISO 8601 date")
    private static class StringDateTime {}
}
```

Expected schema:
```
components:
  schemas:
    MyParameter:
      type: object
      properties:
        date:
          anyOf:
          - type: integer
            format: int64
            description: Unix timestamp
          - type: string
            format: date-time
            description: ISO 8601 date
```

Actual schema:
```
components:
  schemas:
    MyParameter:
      type: object
      properties:
        date:
          type: object
          anyOf:
          - type: integer
            format: int64
            description: Unix timestamp
          - type: string
            format: date-time
            description: ISO 8601 date
          properties:
            epochSecond:
              type: integer
              format: int64
            nano:
              type: integer
              format: int32
```
