### ISSUE TITLE
Explicit schema type specified on `@Parameter` annotation is always ignored

### ISSUE THREAD

**Issue by adriansuarez** [swagger-api/swagger-core#4763]
I am accepting a query parameter within an object in an opaque form so that I can apply Jakarta validation constraints to it, rather than failing to create the object at all and generating a useless message about dependency injection not being able to build the object at all.

I'm declaring a query parameter as a `String` and then parsing it later, as follows:

```java
    @PositiveOrZero
    @Parameter(description = "The offset at which to list items", schema = @Schema(type = "integer", format = "int32"))
    @QueryParam(OFFSET)
    public String offset;
```

Despite this, the schema for the query parameter continues to have `string` as its type:

```yaml
      parameters:
      - name: offset
        in: query
        description: The offset at which to list items
        schema:
          type: string  # should be type: integer
          format: int32
```
