### ISSUE TITLE
Unable to process component annotations on record classes with fields with @JsonProperty annotations differing from field names

### ISSUE THREAD

**Issue by richard-lindsay** [swagger-api/swagger-core#4796]
### Problem 
After upgrading to 2.2.26, record classes with fields annotated with JsonProperty with a value different to the naming of the field are unable to render component annotations, will throw a NoSuchMethodException exception, and log an error for this class. 

### Fix 
Accessing the method object using `propDef.getPrimaryMember().getName())` should prevent this. PR available here: https://github.com/swagger-api/swagger-core/pull/4795

### Example

```java
 record JavaRecordWithJsonPropertyAnnotationNotMatchingFieldName(
    @JsonProperty("listOfStrings") 
    List<@Size(min = 1, max = 5)String> stringList
) { }
```

#### Before 

```
JavaRecordWithJsonPropertyAnnotationNotMatchingFieldName:
    type: object
    properties:
        listOfStrings:
            type: array
            items:
                type: string
```

#### After 
```
JavaRecordWithJsonPropertyAnnotationNotMatchingFieldName:
    type: object
    properties:
        listOfStrings:
            type: array
            items:
                maxLength: 5
                minLength: 1
                type: string
```
