### ISSUE TITLE
invalid YAML for petstore

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-core#762]
For some reason, the security definitions look wrong:

```yaml

securityDefinitions:
  api_key: in: apiKey
    name: "api_key"
    in: "header"
  petstore_auth: in: oauth2
    authorizationUrl: "http://petstore.swagger.wordnik.com/api/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"

```

cc: @earth2marsh
